"""scan revisions

Revision ID: dea3b45e8a67
Revises: e56f1e8b17b2
Create Date: 2026-08-30 12:05:10.367381
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'dea3b45e8a67'
down_revision: str | None = 'e56f1e8b17b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'revision', name='uq_scan_revision')
    )
    with op.batch_alter_table('scan_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_revisions_scan_id'), ['scan_id'], unique=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('revision')

    with op.batch_alter_table('scan_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_revisions_scan_id'))

    op.drop_table('scan_revisions')
    # ### end Alembic commands ###
