"""retention and soft delete

Revision ID: 36da4516ec2c
Revises: dea3b45e8a67
Create Date: 2026-08-30 15:39:56.560393
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '36da4516ec2c'
down_revision: str | None = 'dea3b45e8a67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_open', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('case_open_decided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('case_open_decided_by_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('deleted_reason', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_scans_deleted_by', 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key('fk_scans_case_open_decided_by', 'users', ['case_open_decided_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scans_case_open_decided_by', type_='foreignkey')
        batch_op.drop_constraint('fk_scans_deleted_by', type_='foreignkey')
        batch_op.drop_column('deleted_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('case_open_decided_by_id')
        batch_op.drop_column('case_open_decided_at')
        batch_op.drop_column('case_open')

    # ### end Alembic commands ###
