"""initial schema

Revision ID: 4b536bc66096
Revises: 
Create Date: 2026-08-29 19:44:19.283106
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4b536bc66096'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SENIOR_OFFICER', 'FIELD_INSPECTOR', 'AUDITOR', 'MANUFACTURER', name='role'), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('gtin', sa.String(length=32), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_gtin'), ['gtin'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yaml_blob', sa.Text(), nullable=False),
    sa.Column('published_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_versions_version'), ['version'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('PHYSICAL', 'ECOMMERCE', name='channel'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'EXTRACTING', 'EVALUATING', 'COMPLETE', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=32), nullable=True),
    sa.Column('extractor_version', sa.String(length=64), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('mm_per_px', sa.Float(), nullable=True),
    sa.Column('scale_source', sa.String(length=32), nullable=True),
    sa.Column('scale_confidence', sa.Float(), nullable=True),
    sa.Column('pdp_area_cm2', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'INCONCLUSIVE', name='verdict'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('place_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_product_id'), ['product_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'UNDER_REVIEW', 'VIOLATION_CONFIRMED', 'NOTICE_ISSUED', 'CLOSED', name='casestate'), nullable=False),
    sa.Column('assignee_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_scan_id'), ['scan_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_state'), ['state'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('citation', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'NA', 'NEEDS_REVIEW', name='findingstatus'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('evidence_bbox', sa.JSON(), nullable=True),
    sa.Column('evidence_image_id', sa.String(length=32), nullable=True),
    sa.Column('original_status', sa.Enum('PASS', 'FAIL', 'NA', 'NEEDS_REVIEW', name='findingstatus'), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by_id', sa.String(length=32), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('pdf_key', sa.String(length=255), nullable=True),
    sa.Column('docx_key', sa.String(length=255), nullable=True),
    sa.Column('json_key', sa.String(length=255), nullable=True),
    sa.Column('generated_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_scan_id'), ['scan_id'], unique=True)

    op.create_table('scan_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('FRONT', 'BACK', 'SIDE', 'LISTING', 'EVIDENCE', name='imagekind'), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('ocr_blocks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_images_scan_id'), ['scan_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_image_id', sa.String(length=32), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('glyph_height_mm', sa.Float(), nullable=True),
    sa.Column('glyph_width_mm', sa.Float(), nullable=True),
    sa.Column('extracted_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['source_image_id'], ['scan_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'field_key', name='uq_scan_field')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_scan_id'), ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_scan_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_key'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('scan_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_images_scan_id'))

    op.drop_table('scan_images')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_scan_id'))

    op.drop_table('reports')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_id'))

    op.drop_table('findings')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_state'))
        batch_op.drop_index(batch_op.f('ix_cases_scan_id'))

    op.drop_table('cases')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_product_id'))
        batch_op.drop_index(batch_op.f('ix_scans_created_by_id'))

    op.drop_table('scans')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_version'))
        batch_op.drop_index(batch_op.f('ix_rule_versions_effective_date'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_gtin'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
