"""scan provenance columns

Revision ID: e56f1e8b17b2
Revises: 4b536bc66096
Create Date: 2026-08-29 19:46:59.143839
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e56f1e8b17b2'
down_revision: str | None = '4b536bc66096'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale_detail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('panel_method', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('exemption_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pipeline_notes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('pipeline_notes')
        batch_op.drop_column('exemption_id')
        batch_op.drop_column('panel_method')
        batch_op.drop_column('scale_detail')

    # ### end Alembic commands ###
